local groups = {
    ["@annotation"] = {link = "PreProc"},
    ["@attribute"] = {link = "PreProc"},
    ["@boolean"] = {fg = "#64fcda"},
    ["@character"] = {link = "Character"},
    ["@character.special"] = {link = "SpecialChar"},
    ["@comment"] = {link = "Comment"},
    ["@conceal"] = {},
    ["@conditional"] = {link = "Conditional"},
    ["@constant"] = {link = "Constant"},
    ["@constant.builtin"] = {fg = "#00b0ff"},
    ["@constant.macro"] = {link = "Define"},
    ["@constructor"] = {fg = "#00b0ff"},
    ["@debug"] = {link = "Debug"},
    ["@define"] = {link = "Define"},
    ["@error"] = {link = "Error"},
    ["@exception"] = {link = "Exception"},
    ["@field"] = {link = "Identifier"},
    ["@float"] = {link = "Float"},
    ["@function"] = {link = "Function"},
    ["@function.builtin"] = {link = "Function"},
    ["@function.call"] = {link = "Function"},
    ["@function.macro"] = {link = "Macro"},
    ["@include"] = {link = "Include"},
    ["@include.tsx"] = {fg = "#cbcbcb"},
    ["@include.typescript"] = {fg = "#cbcbcb"},
    ["@keyword"] = {link = "Keyword"},
    ["@keyword.function"] = {fg = "#ffffff"},
    ["@keyword.operator"] = {link = "Operator"},
    ["@keyword.return"] = {fg = "#ffffff"},
    ["@label"] = {link = "Label"},
    ["@lsp"] = {},
    ["@lsp.mod.deprecated"] = {fg = "#9ca3b2", strikethrough = true},
    ["@lsp.mod.documentation"] = {link = "@constant"},
    ["@lsp.type.class"] = {link = "@type"},
    ["@lsp.type.comment"] = {link = "@comment"},
    ["@lsp.type.decorator"] = {},
    ["@lsp.type.enum"] = {link = "@type"},
    ["@lsp.type.enumMember"] = {link = "@constant"},
    ["@lsp.type.function"] = {link = "@function"},
    ["@lsp.type.interface"] = {},
    ["@lsp.type.keyword"] = {link = "@keyword"},
    ["@lsp.type.macro"] = {link = "@function"},
    ["@lsp.type.method"] = {link = "@function"},
    ["@lsp.type.namespace"] = {link = "@namespace"},
    ["@lsp.type.number"] = {link = "@number"},
    ["@lsp.type.operator"] = {link = "@operator"},
    ["@lsp.type.parameter"] = {link = "@parameter"},
    ["@lsp.type.property"] = {link = "@property"},
    ["@lsp.type.string"] = {link = "@string"},
    ["@lsp.type.struct"] = {link = "@type"},
    ["@lsp.type.type"] = {},
    ["@lsp.type.typeParameter"] = {link = "@type"},
    ["@lsp.type.variable"] = {},
    ["@macro"] = {link = "Macro"},
    ["@method"] = {link = "Function"},
    ["@method.call"] = {link = "Function"},
    ["@namespace"] = {link = "Include"},
    ["@none"] = {},
    ["@number"] = {link = "Number"},
    ["@operator"] = {link = "Operator"},
    ["@parameter"] = {fg = "#d19a66"},
    ["@parameter.reference"] = {link = "@parameter"},
    ["@preproc"] = {link = "PreProc"},
    ["@property"] = {link = "Identifier"},
    ["@punctuation"] = {link = "Delimiter"},
    ["@punctuation.bracket"] = {link = "Delimiter"},
    ["@punctuation.delimiter"] = {link = "Delimiter"},
    ["@punctuation.special"] = {link = "Delimiter"},
    ["@repeat"] = {link = "Repeat"},
    ["@spell"] = {},
    ["@storageclass"] = {link = "StorageClass"},
    ["@string"] = {link = "String"},
    ["@string.escape"] = {link = "SpecialChar"},
    ["@string.regex"] = {link = "String"},
    ["@string.special"] = {link = "SpecialChar"},
    ["@symbol"] = {link = "Identifier"},
    ["@tag"] = {link = "Label"},
    ["@tag.attribute"] = {link = "Identifier"},
    ["@tag.delimiter"] = {link = "Delimiter"},
    ["@text"] = {link = "Normal"},
    ["@text.danger"] = {link = "WarningMsg"},
    ["@text.emphasis"] = {},
    ["@text.environment"] = {link = "Macro"},
    ["@text.environment.name"] = {link = "Type"},
    ["@text.literal"] = {link = "String"},
    ["@text.math"] = {link = "Special"},
    ["@text.note"] = {link = "SpecialComment"},
    ["@text.reference"] = {link = "Constant"},
    ["@text.strike"] = {strikethrough = true},
    ["@text.strong"] = {bold = true},
    ["@text.title"] = {link = "Title"},
    ["@text.todo"] = {link = "Todo"},
    ["@text.underline"] = {underline = true},
    ["@text.uri"] = {fg = "#00b0ff", undercurl = true},
    ["@text.warning"] = {link = "WarningMsg"},
    ["@todo"] = {link = "Todo"},
    ["@type"] = {link = "Type"},
    ["@type.builtin"] = {link = "Type"},
    ["@type.definition"] = {link = "Typedef"},
    ["@type.qualifier"] = {link = "Type"},
    ["@variable"] = {fg = "#b0bec4"},
    ["@variable.builtin"] = {fg = "#ffffff"},
    Beacon = {},
    BeaconDefault = {},
    Boolean = {fg = "#64fcda"},
    BufferLineBackground = {fg = "#676e7b"},
    BufferLineBuffer = {fg = "#676e7b"},
    BufferLineBufferSelected = {bold = true, fg = "#b0bec4", italic = true},
    BufferLineBufferVisible = {fg = "#676e7b"},
    BufferLineCloseButton = {fg = "#676e7b"},
    BufferLineCloseButtonSelected = {fg = "#b0bec4"},
    BufferLineCloseButtonVisible = {fg = "#676e7b"},
    BufferLineDiagnostic = {fg = "#313244"},
    BufferLineDiagnosticSelected = {bold = true, fg = "#9ca3b2"},
    BufferLineDiagnosticVisible = {fg = "#313244"},
    BufferLineDuplicate = {fg = "#616874", italic = true},
    BufferLineDuplicateSelected = {fg = "#616874", italic = true},
    BufferLineDuplicateVisible = {fg = "#616874", italic = true},
    BufferLineError = {fg = "#676e7b", sp = "#d54e53"},
    BufferLineErrorDiagnostic = {fg = "#313244", sp = "#d54e53"},
    BufferLineErrorDiagnosticSelected = {
        bold = true,
        fg = "#d54e53",
        sp = "#d54e53"
    },
    BufferLineErrorDiagnosticVisible = {fg = "#d54e53"},
    BufferLineErrorSelected = {
        bold = true,
        fg = "#d54e53",
        italic = true,
        sp = "#d54e53"
    },
    BufferLineErrorVisible = {fg = "#676e7b"},
    BufferLineFill = {fg = "#676e7b"},
    BufferLineGroupLabel = {bg = "#676e7b"},
    BufferLineGroupSeparator = {fg = "#676e7b"},
    BufferLineHint = {fg = "#676e7b", sp = "#9ca3b2"},
    BufferLineHintDiagnostic = {fg = "#313244", sp = "#9ca3b2"},
    BufferLineHintDiagnosticSelected = {
        bold = true,
        fg = "#9ca3b2",
        sp = "#9ca3b2"
    },
    BufferLineHintDiagnosticVisible = {fg = "#9ca3b2"},
    BufferLineHintSelected = {
        bold = true,
        fg = "#9ca3b2",
        italic = true,
        sp = "#9ca3b2"
    },
    BufferLineHintVisible = {fg = "#676e7b"},
    BufferLineIndicatorSelected = {fg = "#00b0ff"},
    BufferLineIndicatorVisible = {},
    BufferLineInfo = {fg = "#676e7b", sp = "#fefefe"},
    BufferLineInfoDiagnostic = {fg = "#313244", sp = "#3dd177"},
    BufferLineInfoDiagnosticSelected = {
        bold = true,
        fg = "#3dd177",
        sp = "#3dd177"
    },
    BufferLineInfoDiagnosticVisible = {fg = "#3dd177"},
    BufferLineInfoSelected = {
        bold = true,
        fg = "#fefefe",
        italic = true,
        sp = "#fefefe"
    },
    BufferLineInfoVisible = {fg = "#676e7b"},
    BufferLineModified = {fg = "#ffffff"},
    BufferLineModifiedSelected = {fg = "#ffffff"},
    BufferLineModifiedVisible = {fg = "#ffffff"},
    BufferLineNumbers = {fg = "#c678dd"},
    BufferLineNumbersSelected = {fg = "#c678dd"},
    BufferLineNumbersVisible = {fg = "#c678dd"},
    BufferLineOffsetSeparator = {fg = "#b0bec4"},
    BufferLinePick = {bold = true, fg = "#d54e53", italic = true},
    BufferLinePickSelected = {bold = true, fg = "#d54e53", italic = true},
    BufferLinePickVisible = {bold = true, fg = "#d54e53", italic = true},
    BufferLineSeparator = {},
    BufferLineSeparatorSelected = {},
    BufferLineSeparatorVisible = {},
    BufferLineTab = {fg = "#676e7b"},
    BufferLineTabClose = {fg = "#676e7b"},
    BufferLineTabSelected = {fg = "#000000"},
    BufferLineTabSeparator = {},
    BufferLineTabSeparatorSelected = {},
    BufferLineTruncMarker = {fg = "#676e7b"},
    BufferLineWarning = {fg = "#676e7b", sp = "#ffc900"},
    BufferLineWarningDiagnostic = {fg = "#313244", sp = "#ffc900"},
    BufferLineWarningDiagnosticSelected = {
        bold = true,
        fg = "#ffc900",
        sp = "#ffc900"
    },
    BufferLineWarningDiagnosticVisible = {fg = "#ffc900"},
    BufferLineWarningSelected = {
        bold = true,
        fg = "#ffc900",
        italic = true,
        sp = "#ffc900"
    },
    BufferLineWarningVisible = {fg = "#676e7b"},
    Character = {fg = "#ffc900"},
    CmpItemAbbr = {link = "CmpItemAbbrDefault"},
    CmpItemAbbrDefault = {fg = "#b0bec4"},
    CmpItemAbbrDeprecated = {fg = "#9ca3b2", strikethrough = true},
    CmpItemAbbrDeprecatedDefault = {fg = "#676e7b"},
    CmpItemAbbrMatch = {fg = "#00b0ff"},
    CmpItemAbbrMatchDefault = {fg = "#b0bec4"},
    CmpItemAbbrMatchFuzzy = {link = "CmpItemAbbrMatch"},
    CmpItemAbbrMatchFuzzyDefault = {fg = "#b0bec4"},
    CmpItemKind = {link = "CmpItemKindDefault"},
    CmpItemKindClass = {fg = "#ffffff"},
    CmpItemKindClassDefault = {link = "CmpItemKind"},
    CmpItemKindColor = {link = "CmpItemKindColorDefault"},
    CmpItemKindColorDefault = {link = "CmpItemKind"},
    CmpItemKindConstant = {fg = "#64fcda"},
    CmpItemKindConstantDefault = {link = "CmpItemKind"},
    CmpItemKindConstructor = {link = "@constructor"},
    CmpItemKindConstructorDefault = {link = "CmpItemKind"},
    CmpItemKindCopilot = {},
    CmpItemKindDefault = {fg = "#c678dd"},
    CmpItemKindEnum = {fg = "#64fcda"},
    CmpItemKindEnumDefault = {link = "CmpItemKind"},
    CmpItemKindEnumMember = {fg = "#ffc900"},
    CmpItemKindEnumMemberDefault = {link = "CmpItemKind"},
    CmpItemKindEvent = {fg = "#ffc900"},
    CmpItemKindEventDefault = {link = "CmpItemKind"},
    CmpItemKindField = {fg = "#ffc900"},
    CmpItemKindFieldDefault = {link = "CmpItemKind"},
    CmpItemKindFile = {fg = "#fefefe"},
    CmpItemKindFileDefault = {link = "CmpItemKind"},
    CmpItemKindFolder = {fg = "#ffc900"},
    CmpItemKindFolderDefault = {link = "CmpItemKind"},
    CmpItemKindFunction = {link = "Function"},
    CmpItemKindFunctionDefault = {link = "CmpItemKind"},
    CmpItemKindInterface = {fg = "#ffffff"},
    CmpItemKindInterfaceDefault = {link = "CmpItemKind"},
    CmpItemKindKeyword = {fg = "#fefefe"},
    CmpItemKindKeywordDefault = {link = "CmpItemKind"},
    CmpItemKindMethod = {link = "Function"},
    CmpItemKindMethodDefault = {link = "CmpItemKind"},
    CmpItemKindModule = {fg = "#ffffff"},
    CmpItemKindModuleDefault = {link = "CmpItemKind"},
    CmpItemKindOperator = {link = "Operator"},
    CmpItemKindOperatorDefault = {link = "CmpItemKind"},
    CmpItemKindProperty = {fg = "#ffc900"},
    CmpItemKindPropertyDefault = {link = "CmpItemKind"},
    CmpItemKindReference = {link = "CmpItemKindReferenceDefault"},
    CmpItemKindReferenceDefault = {link = "CmpItemKind"},
    CmpItemKindSnippet = {link = "CmpItemKindSnippetDefault"},
    CmpItemKindSnippetDefault = {link = "CmpItemKind"},
    CmpItemKindStruct = {fg = "#ffffff"},
    CmpItemKindStructDefault = {link = "CmpItemKind"},
    CmpItemKindText = {fg = "#fefefe"},
    CmpItemKindTextDefault = {link = "CmpItemKind"},
    CmpItemKindTypeParameter = {link = "CmpItemKindTypeParameterDefault"},
    CmpItemKindTypeParameterDefault = {link = "CmpItemKind"},
    CmpItemKindUnit = {fg = "#d19a66"},
    CmpItemKindUnitDefault = {link = "CmpItemKind"},
    CmpItemKindValue = {fg = "#fefefe"},
    CmpItemKindValueDefault = {link = "CmpItemKind"},
    CmpItemKindVariable = {fg = "#64fcda"},
    CmpItemKindVariableDefault = {link = "CmpItemKind"},
    CmpItemMenu = {link = "CmpItemMenuDefault"},
    CmpItemMenuDefault = {fg = "#b0bec4"},
    ColorColumn = {bg = "#26292f"},
    Comment = {fg = "#676e7b"},
    Conceal = {fg = "#9ca3b2"},
    Conditional = {link = "Statement"},
    Constant = {fg = "#00b0ff"},
    CopilotAnnotation = {link = "Comment"},
    CopilotSuggestion = {link = "Comment"},
    CratesNvimError = {fg = "#d54e53"},
    CratesNvimLoading = {fg = "#c678dd"},
    CratesNvimNoMatch = {fg = "#ffffff"},
    CratesNvimPopupEnabled = {fg = "#3dd177"},
    CratesNvimPopupFeature = {fg = "#00b0ff"},
    CratesNvimPopupPreRelease = {fg = "#64fcda"},
    CratesNvimPopupTitle = {fg = "#c678dd"},
    CratesNvimPopupTransitive = {fg = "#ffffff"},
    CratesNvimPopupUrl = {fg = "#00b0ff"},
    CratesNvimPopupVersion = {fg = "#3dd177"},
    CratesNvimPopupYanked = {fg = "#ffffff"},
    CratesNvimPreRelease = {fg = "#64fcda"},
    CratesNvimUpgrade = {fg = "#ffc900"},
    CratesNvimVersion = {fg = "#3dd177"},
    CratesNvimYanked = {fg = "#d54e53"},
    CurSearch = {link = "Search"},
    Cursor = {bg = "#b0bec4", fg = "#18191a"},
    CursorColumn = {bg = "#383a3e"},
    CursorLine = {bg = "#383a3e"},
    CursorLineFold = {link = "FoldColumn"},
    CursorLineNr = {fg = "#b0bec4"},
    CursorLineSign = {link = "SignColumn"},
    DapUIBreakpointsCurrentLine = {bold = true, fg = "#a9ff68"},
    DapUIBreakpointsDisabledLine = {fg = "#424242"},
    DapUIBreakpointsInfo = {fg = "#a9ff68"},
    DapUIBreakpointsLine = {link = "DapUILineNumber"},
    DapUIBreakpointsPath = {fg = "#00f1f5"},
    DapUICurrentFrameName = {link = "DapUIBreakpointsCurrentLine"},
    DapUIDecoration = {fg = "#00f1f5"},
    DapUIEndofBuffer = {link = "EndOfBuffer"},
    DapUIFloatBorder = {fg = "#00f1f5"},
    DapUIFloatNormal = {link = "NormalFloat"},
    DapUIFrameName = {link = "Normal"},
    DapUILineNumber = {fg = "#00f1f5"},
    DapUIModifiedValue = {bold = true, fg = "#00f1f5"},
    DapUINormal = {link = "Normal"},
    DapUINormalNC = {fg = "#b0bec4"},
    DapUIPlayPause = {fg = "#a9ff68"},
    DapUIPlayPauseNC = {fg = "#a9ff68"},
    DapUIRestart = {fg = "#a9ff68"},
    DapUIRestartNC = {fg = "#a9ff68"},
    DapUIScope = {fg = "#00f1f5"},
    DapUISource = {fg = "#d484ff"},
    DapUIStepBack = {fg = "#00f1f5"},
    DapUIStepBackNC = {fg = "#00f1f5"},
    DapUIStepInto = {fg = "#00f1f5"},
    DapUIStepIntoNC = {fg = "#00f1f5"},
    DapUIStepOut = {fg = "#00f1f5"},
    DapUIStepOutNC = {fg = "#00f1f5"},
    DapUIStepOver = {fg = "#00f1f5"},
    DapUIStepOverNC = {fg = "#00f1f5"},
    DapUIStop = {fg = "#f70067"},
    DapUIStopNC = {fg = "#f70067"},
    DapUIStoppedThread = {fg = "#00f1f5"},
    DapUIThread = {fg = "#a9ff68"},
    DapUIType = {fg = "#d484ff"},
    DapUIUnavailable = {fg = "#424242"},
    DapUIUnavailableNC = {fg = "#424242"},
    DapUIValue = {link = "Normal"},
    DapUIVariable = {link = "Normal"},
    DapUIWatchesEmpty = {fg = "#f70067"},
    DapUIWatchesError = {fg = "#f70067"},
    DapUIWatchesValue = {fg = "#a9ff68"},
    DapUIWinSelect = {bold = true, ctermfg = 14, fg = "#00f1f5"},
    DashboardCenter = {fg = "#ffffff"},
    DashboardFooter = {fg = "#00b0ff"},
    DashboardHeader = {fg = "#f6d5a4"},
    Debug = {link = "Special"},
    Define = {fg = "#ffffff"},
    Delimiter = {fg = "#ffffff"},
    DevIconAi = {ctermfg = 185, fg = "#cbcb41"},
    DevIconAwk = {ctermfg = 240, fg = "#4d5a5e"},
    DevIconBabelrc = {ctermfg = 185, fg = "#cbcb41"},
    DevIconBash = {ctermfg = 113, fg = "#89e051"},
    DevIconBashProfile = {ctermfg = 113, fg = "#89e051"},
    DevIconBashrc = {ctermfg = 113, fg = "#89e051"},
    DevIconBat = {ctermfg = 191, fg = "#c1f12e"},
    DevIconBazel = {ctermfg = 113, fg = "#89e051"},
    DevIconBazelBuild = {ctermfg = 113, fg = "#89e051"},
    DevIconBazelWorkspace = {ctermfg = 113, fg = "#89e051"},
    DevIconBinaryGLTF = {ctermfg = 214, fg = "#ffb13b"},
    DevIconBmp = {ctermfg = 140, fg = "#a074c4"},
    DevIconBrewfile = {ctermfg = 52, fg = "#701516"},
    DevIconBzl = {ctermfg = 113, fg = "#89e051"},
    DevIconC = {ctermfg = 111, fg = "#599eff"},
    DevIconCMake = {ctermfg = 66, fg = "#6d8086"},
    DevIconCMakeLists = {ctermfg = 66, fg = "#6d8086"},
    DevIconCPlusPlus = {ctermfg = 204, fg = "#f34b7d"},
    DevIconCjs = {ctermfg = 185, fg = "#cbcb41"},
    DevIconClojure = {ctermfg = 113, fg = "#8dc149"},
    DevIconClojureC = {ctermfg = 113, fg = "#8dc149"},
    DevIconClojureDart = {ctermfg = 74, fg = "#519aba"},
    DevIconClojureJS = {ctermfg = 74, fg = "#519aba"},
    DevIconCobol = {ctermfg = 25, fg = "#005ca5"},
    DevIconCoffee = {ctermfg = 185, fg = "#cbcb41"},
    DevIconConf = {ctermfg = 66, fg = "#6d8086"},
    DevIconConfigRu = {ctermfg = 52, fg = "#701516"},
    DevIconConfiguration = {ctermfg = 255, fg = "#ececec"},
    DevIconCp = {ctermfg = 74, fg = "#519aba"},
    DevIconCpp = {ctermfg = 74, fg = "#519aba"},
    DevIconCrystal = {ctermfg = 251, fg = "#c8c8c8"},
    DevIconCs = {ctermfg = 58, fg = "#596706"},
    DevIconCsh = {ctermfg = 240, fg = "#4d5a5e"},
    DevIconCson = {ctermfg = 185, fg = "#cbcb41"},
    DevIconCss = {ctermfg = 75, fg = "#42a5f5"},
    DevIconCsv = {ctermfg = 113, fg = "#89e051"},
    DevIconCxx = {ctermfg = 74, fg = "#519aba"},
    DevIconD = {ctermfg = 28, fg = "#427819"},
    DevIconDart = {ctermfg = 25, fg = "#03589c"},
    DevIconDb = {ctermfg = 188, fg = "#dad8d8"},
    DevIconDefault = {ctermfg = 66, fg = "#6d8086"},
    DevIconDesktopEntry = {ctermfg = 54, fg = "#563d7c"},
    DevIconDiff = {ctermfg = 239, fg = "#41535b"},
    DevIconDoc = {ctermfg = 26, fg = "#185abd"},
    DevIconDockerfile = {ctermfg = 68, fg = "#458ee6"},
    DevIconDocx = {ctermfg = 26, fg = "#185abd"},
    DevIconDrools = {ctermfg = 217, fg = "#ffafaf"},
    DevIconDropbox = {ctermfg = 27, fg = "#0061fe"},
    DevIconDsStore = {ctermfg = 239, fg = "#41535b"},
    DevIconDump = {ctermfg = 188, fg = "#dad8d8"},
    DevIconEdn = {ctermfg = 74, fg = "#519aba"},
    DevIconEex = {ctermfg = 140, fg = "#a074c4"},
    DevIconEjs = {ctermfg = 185, fg = "#cbcb41"},
    DevIconElm = {ctermfg = 74, fg = "#519aba"},
    DevIconEnv = {ctermfg = 227, fg = "#faf743"},
    DevIconEpp = {fg = "#ffa61a"},
    DevIconErb = {ctermfg = 214, fg = "#701516"},
    DevIconErl = {ctermfg = 163, fg = "#b83998"},
    DevIconEslintrc = {ctermfg = 56, fg = "#4b32c3"},
    DevIconEx = {ctermfg = 140, fg = "#a074c4"},
    DevIconExs = {ctermfg = 140, fg = "#a074c4"},
    DevIconFavicon = {ctermfg = 185, fg = "#cbcb41"},
    DevIconFennel = {ctermfg = 230, fg = "#fff3d7"},
    DevIconFish = {ctermfg = 240, fg = "#4d5a5e"},
    DevIconFortran = {ctermfg = 97, fg = "#734f96"},
    DevIconFs = {ctermfg = 74, fg = "#519aba"},
    DevIconFsharp = {ctermfg = 74, fg = "#519aba"},
    DevIconFsi = {ctermfg = 74, fg = "#519aba"},
    DevIconFsscript = {ctermfg = 74, fg = "#519aba"},
    DevIconFsx = {ctermfg = 74, fg = "#519aba"},
    DevIconGDScript = {ctermfg = 66, fg = "#6d8086"},
    DevIconGemfile = {ctermfg = 52, fg = "#701516"},
    DevIconGemspec = {ctermfg = 52, fg = "#701516"},
    DevIconGif = {ctermfg = 140, fg = "#a074c4"},
    DevIconGitAttributes = {ctermfg = 239, fg = "#41535b"},
    DevIconGitCommit = {ctermfg = 239, fg = "#41535b"},
    DevIconGitConfig = {ctermfg = 239, fg = "#41535b"},
    DevIconGitIgnore = {ctermfg = 239, fg = "#41535b"},
    DevIconGitLogo = {ctermfg = 196, fg = "#f14c28"},
    DevIconGitModules = {ctermfg = 239, fg = "#41535b"},
    DevIconGitlabCI = {ctermfg = 196, fg = "#e24329"},
    DevIconGo = {ctermfg = 74, fg = "#519aba"},
    DevIconGodotProject = {ctermfg = 66, fg = "#6d8086"},
    DevIconGraphQL = {ctermfg = 199, fg = "#e535ab"},
    DevIconGruntfile = {ctermfg = 166, fg = "#e37933"},
    DevIconGulpfile = {ctermfg = 167, fg = "#cc3e44"},
    DevIconGvimrc = {ctermfg = 28, fg = "#019833"},
    DevIconH = {ctermfg = 140, fg = "#a074c4"},
    DevIconHaml = {ctermfg = 255, fg = "#eaeae1"},
    DevIconHbs = {ctermfg = 202, fg = "#f0772b"},
    DevIconHeex = {ctermfg = 140, fg = "#a074c4"},
    DevIconHh = {ctermfg = 140, fg = "#a074c4"},
    DevIconHpp = {ctermfg = 140, fg = "#a074c4"},
    DevIconHrl = {ctermfg = 163, fg = "#b83998"},
    DevIconHs = {ctermfg = 140, fg = "#a074c4"},
    DevIconHtm = {ctermfg = 196, fg = "#e34c26"},
    DevIconHtml = {ctermfg = 196, fg = "#e44d26"},
    DevIconHxx = {ctermfg = 140, fg = "#a074c4"},
    DevIconIco = {ctermfg = 185, fg = "#cbcb41"},
    DevIconImportConfiguration = {ctermfg = 255, fg = "#ececec"},
    DevIconIni = {ctermfg = 66, fg = "#6d8086"},
    DevIconJava = {ctermfg = 167, fg = "#cc3e44"},
    DevIconJavaScriptReactSpec = {ctermfg = 45, fg = "#20c2e3"},
    DevIconJavaScriptReactTest = {ctermfg = 45, fg = "#20c2e3"},
    DevIconJl = {ctermfg = 133, fg = "#a270ba"},
    DevIconJpeg = {ctermfg = 140, fg = "#a074c4"},
    DevIconJpg = {ctermfg = 140, fg = "#a074c4"},
    DevIconJs = {ctermfg = 185, fg = "#cbcb41"},
    DevIconJson = {ctermfg = 185, fg = "#cbcb41"},
    DevIconJson5 = {ctermfg = 185, fg = "#cbcb41"},
    DevIconJsx = {ctermfg = 45, fg = "#20c2e3"},
    DevIconKotlin = {ctermfg = 99, fg = "#7f52ff"},
    DevIconKotlinScript = {ctermfg = 99, fg = "#7f52ff"},
    DevIconKsh = {ctermfg = 240, fg = "#4d5a5e"},
    DevIconLeex = {ctermfg = 140, fg = "#a074c4"},
    DevIconLess = {ctermfg = 54, fg = "#563d7c"},
    DevIconLhs = {ctermfg = 140, fg = "#a074c4"},
    DevIconLicense = {ctermfg = 185, fg = "#cbcb41"},
    DevIconLiquid = {ctermfg = 106, fg = "#95bf47"},
    DevIconLock = {ctermfg = 250, fg = "#bbbbbb"},
    DevIconLog = {ctermfg = 231, fg = "#ffffff"},
    DevIconLua = {ctermfg = 74, fg = "#51a0cf"},
    DevIconLuau = {ctermfg = 74, fg = "#51a0cf"},
    DevIconMakefile = {ctermfg = 66, fg = "#6d8086"},
    DevIconMarkdown = {ctermfg = 74, fg = "#519aba"},
    DevIconMaterial = {ctermfg = 163, fg = "#b83998"},
    DevIconMd = {ctermfg = 231, fg = "#ffffff"},
    DevIconMdx = {ctermfg = 74, fg = "#519aba"},
    DevIconMint = {ctermfg = 108, fg = "#87c095"},
    DevIconMixLock = {ctermfg = 140, fg = "#a074c4"},
    DevIconMjs = {ctermfg = 185, fg = "#f1e05a"},
    DevIconMl = {ctermfg = 166, fg = "#e37933"},
    DevIconMli = {ctermfg = 166, fg = "#e37933"},
    DevIconMotoko = {ctermfg = 135, fg = "#9772fb"},
    DevIconMustache = {ctermfg = 166, fg = "#e37933"},
    DevIconNPMIgnore = {ctermfg = 197, fg = "#e8274b"},
    DevIconNPMrc = {ctermfg = 197, fg = "#e8274b"},
    DevIconNim = {ctermfg = 220, fg = "#f3d400"},
    DevIconNix = {ctermfg = 110, fg = "#7ebae4"},
    DevIconNodeModules = {ctermfg = 197, fg = "#e8274b"},
    DevIconOPUS = {ctermfg = 208, fg = "#f88a02"},
    DevIconOpenTypeFont = {ctermfg = 255, fg = "#ececec"},
    DevIconOrgMode = {ctermfg = 73, fg = "#77aa99"},
    DevIconPackageJson = {fg = "#e8274b"},
    DevIconPackageLockJson = {fg = "#7a0d21"},
    DevIconPackedResource = {ctermfg = 66, fg = "#6d8086"},
    DevIconPdf = {ctermfg = 124, fg = "#b30b00"},
    DevIconPhp = {ctermfg = 140, fg = "#a074c4"},
    DevIconPl = {ctermfg = 74, fg = "#519aba"},
    DevIconPm = {ctermfg = 74, fg = "#519aba"},
    DevIconPng = {ctermfg = 140, fg = "#a074c4"},
    DevIconPp = {fg = "#ffa61a"},
    DevIconPpt = {ctermfg = 214, fg = "#cb4a32"},
    DevIconPrisma = {ctermfg = 231, fg = "#ffffff"},
    DevIconProcfile = {ctermfg = 140, fg = "#a074c4"},
    DevIconProlog = {ctermfg = 179, fg = "#e4b854"},
    DevIconPsManifestfile = {ctermfg = 68, fg = "#6975c4"},
    DevIconPsScriptModulefile = {ctermfg = 68, fg = "#6975c4"},
    DevIconPsScriptfile = {ctermfg = 68, fg = "#4273ca"},
    DevIconPsb = {ctermfg = 74, fg = "#519aba"},
    DevIconPsd = {ctermfg = 74, fg = "#519aba"},
    DevIconPy = {ctermfg = 214, fg = "#ffbc03"},
    DevIconPyc = {ctermfg = 222, fg = "#ffe291"},
    DevIconPyd = {ctermfg = 222, fg = "#ffe291"},
    DevIconPyo = {ctermfg = 222, fg = "#ffe291"},
    DevIconQuery = {ctermfg = 107, fg = "#90a850"},
    DevIconR = {ctermfg = 29, fg = "#358a5b"},
    DevIconRake = {ctermfg = 52, fg = "#701516"},
    DevIconRakefile = {ctermfg = 52, fg = "#701516"},
    DevIconRb = {ctermfg = 52, fg = "#701516"},
    DevIconReScript = {ctermfg = 167, fg = "#cc3e44"},
    DevIconReScriptInterface = {ctermfg = 204, fg = "#f55385"},
    DevIconRlib = {ctermfg = 216, fg = "#dea584"},
    DevIconRmd = {ctermfg = 74, fg = "#519aba"},
    DevIconRproj = {ctermfg = 29, fg = "#358a5b"},
    DevIconRs = {ctermfg = 216, fg = "#dea584"},
    DevIconRss = {ctermfg = 215, fg = "#fb9d3b"},
    DevIconSass = {ctermfg = 204, fg = "#f55385"},
    DevIconScala = {ctermfg = 167, fg = "#cc3e44"},
    DevIconScheme = {ctermfg = 16, fg = "#000000"},
    DevIconScss = {ctermfg = 204, fg = "#f55385"},
    DevIconSettingsJson = {ctermfg = 98, fg = "#854cc7"},
    DevIconSh = {ctermfg = 240, fg = "#4d5a5e"},
    DevIconSig = {ctermfg = 166, fg = "#e37933"},
    DevIconSlim = {ctermfg = 196, fg = "#e34c26"},
    DevIconSln = {ctermfg = 98, fg = "#854cc7"},
    DevIconSml = {ctermfg = 166, fg = "#e37933"},
    DevIconSolidity = {ctermfg = 74, fg = "#519aba"},
    DevIconSpecJs = {ctermfg = 185, fg = "#cbcb41"},
    DevIconSpecTs = {ctermfg = 74, fg = "#519aba"},
    DevIconSql = {ctermfg = 188, fg = "#dad8d8"},
    DevIconStyl = {ctermfg = 113, fg = "#8dc149"},
    DevIconSuo = {ctermfg = 98, fg = "#854cc7"},
    DevIconSvelte = {ctermfg = 196, fg = "#ff3e00"},
    DevIconSvg = {ctermfg = 214, fg = "#ffb13b"},
    DevIconSwift = {ctermfg = 166, fg = "#e37933"},
    DevIconSystemVerilog = {ctermfg = 28, fg = "#019833"},
    DevIconTFVars = {ctermfg = 93, fg = "#5f43e9"},
    DevIconTcl = {ctermfg = 25, fg = "#1e5cb3"},
    DevIconTerminal = {ctermfg = 34, fg = "#31b53e"},
    DevIconTerraform = {ctermfg = 93, fg = "#5f43e9"},
    DevIconTestJs = {ctermfg = 185, fg = "#cbcb41"},
    DevIconTestTs = {ctermfg = 74, fg = "#519aba"},
    DevIconTex = {ctermfg = 22, fg = "#3d6117"},
    DevIconTextResource = {ctermfg = 185, fg = "#cbcb41"},
    DevIconTextScene = {ctermfg = 140, fg = "#a074c4"},
    DevIconToml = {ctermfg = 66, fg = "#6d8086"},
    DevIconTor = {ctermfg = 74, fg = "#519aba"},
    DevIconTs = {ctermfg = 74, fg = "#519aba"},
    DevIconTsx = {ctermfg = 26, fg = "#1354bf"},
    DevIconTwig = {ctermfg = 113, fg = "#8dc149"},
    DevIconTxt = {ctermfg = 113, fg = "#89e051"},
    DevIconTypeScriptReactSpec = {ctermfg = 26, fg = "#1354bf"},
    DevIconTypeScriptReactTest = {ctermfg = 26, fg = "#1354bf"},
    DevIconVHDL = {ctermfg = 28, fg = "#019833"},
    DevIconVagrantfile = {ctermfg = 27, fg = "#1563ff"},
    DevIconVala = {ctermfg = 91, fg = "#7239b3"},
    DevIconVerilog = {ctermfg = 28, fg = "#019833"},
    DevIconVim = {ctermfg = 28, fg = "#019833"},
    DevIconVimrc = {ctermfg = 28, fg = "#019833"},
    DevIconVlang = {ctermfg = 67, fg = "#5d87bf"},
    DevIconVue = {ctermfg = 113, fg = "#8dc149"},
    DevIconWasm = {ctermfg = 62, fg = "#5c4cdb"},
    DevIconWebmanifest = {ctermfg = 185, fg = "#f1e05a"},
    DevIconWebp = {ctermfg = 140, fg = "#a074c4"},
    DevIconWebpack = {ctermfg = 74, fg = "#519aba"},
    DevIconXcPlayground = {ctermfg = 166, fg = "#e37933"},
    DevIconXls = {ctermfg = 29, fg = "#207245"},
    DevIconXlsx = {ctermfg = 29, fg = "#207245"},
    DevIconXml = {ctermfg = 166, fg = "#e37933"},
    DevIconXul = {ctermfg = 166, fg = "#e37933"},
    DevIconYaml = {ctermfg = 66, fg = "#6d8086"},
    DevIconYml = {ctermfg = 66, fg = "#6d8086"},
    DevIconZig = {ctermfg = 172, fg = "#f69a1b"},
    DevIconZsh = {ctermfg = 113, fg = "#89e051"},
    DevIconZshenv = {ctermfg = 113, fg = "#89e051"},
    DevIconZshprofile = {ctermfg = 113, fg = "#89e051"},
    DevIconZshrc = {ctermfg = 113, fg = "#89e051"},
    DevIconsbt = {ctermfg = 167, fg = "#cc3e44"},
    DiagnosticDeprecated = {sp = "#ff0000", strikethrough = true},
    DiagnosticError = {fg = "#d54e53"},
    DiagnosticFloatingError = {link = "DiagnosticError"},
    DiagnosticFloatingHint = {link = "DiagnosticHint"},
    DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
    DiagnosticFloatingOk = {link = "DiagnosticOk"},
    DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
    DiagnosticHint = {fg = "#9ca3b2"},
    DiagnosticInfo = {fg = "#fefefe"},
    DiagnosticOk = {ctermfg = 10, fg = "#90ee90"},
    DiagnosticOther = {},
    DiagnosticSignError = {link = "DiagnosticError"},
    DiagnosticSignHint = {link = "DiagnosticHint"},
    DiagnosticSignInfo = {link = "DiagnosticInfo"},
    DiagnosticSignOk = {link = "DiagnosticOk"},
    DiagnosticSignOther = {},
    DiagnosticSignWarn = {link = "DiagnosticWarn"},
    DiagnosticUnderlineError = {sp = "#d54e53", underline = true},
    DiagnosticUnderlineHint = {sp = "#9ca3b2", underline = true},
    DiagnosticUnderlineInfo = {sp = "#3dd177", underline = true},
    DiagnosticUnderlineOk = {sp = "#90ee90", underline = true},
    DiagnosticUnderlineWarn = {sp = "#ffc900", underline = true},
    DiagnosticUnnecessary = {link = "Comment"},
    DiagnosticVirtualTextError = {link = "DiagnosticError"},
    DiagnosticVirtualTextHint = {link = "DiagnosticHint"},
    DiagnosticVirtualTextInfo = {link = "DiagnosticInfo"},
    DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
    DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
    DiagnosticWarn = {fg = "#ffc900"},
    DiffAdd = {bg = "#123f24"},
    DiffChange = {fg = "#4c4c4c"},
    DiffDelete = {bg = "#401719"},
    DiffText = {bg = "#1e4c41"},
    DiffviewCursorLine = {bg = "#383a3e"},
    DiffviewDiffAdd = {bg = "#123f24"},
    DiffviewDiffAddAsDelete = {bg = "#401719"},
    DiffviewDiffChange = {fg = "#4c4c4c"},
    DiffviewDiffDelete = {bg = "#401719"},
    DiffviewDiffDeleteDim = {fg = "#676e7b"},
    DiffviewDiffText = {bg = "#1e4c41"},
    DiffviewDim1 = {fg = "#676e7b"},
    DiffviewEndOfBuffer = {fg = "#313244"},
    DiffviewFilePanelConflicts = {fg = "#ffc900"},
    DiffviewFilePanelCounter = {bold = true, fg = "#ffffff"},
    DiffviewFilePanelDeletions = {fg = "#ffffff"},
    DiffviewFilePanelFileName = {fg = "#b0bec4"},
    DiffviewFilePanelInsertions = {fg = "#3dd177"},
    DiffviewFilePanelPath = {fg = "#676e7b"},
    DiffviewFilePanelRootPath = {bold = true, fg = "#ffffff"},
    DiffviewFilePanelSelected = {fg = "#00b0ff"},
    DiffviewFilePanelTitle = {bold = true, fg = "#ffffff"},
    DiffviewFolderName = {fg = "#00b0ff"},
    DiffviewFolderSign = {fg = "#3dd177"},
    DiffviewNonText = {fg = "#313244"},
    DiffviewNormal = {fg = "#b0bec4"},
    DiffviewPrimary = {fg = "#3dd177"},
    DiffviewReference = {fg = "#3dd177"},
    DiffviewSecondary = {fg = "#ffe47e"},
    DiffviewSignColumn = {fg = "#b0bec4"},
    DiffviewStatusAdded = {fg = "#3dd177"},
    DiffviewStatusBroken = {fg = "#ffffff"},
    DiffviewStatusCopied = {fg = "#fefefe"},
    DiffviewStatusDeleted = {fg = "#ffffff"},
    DiffviewStatusIgnored = {fg = "#676e7b"},
    DiffviewStatusLine = {bg = "#1e2024", fg = "#9ca3b2"},
    DiffviewStatusLineNC = {bg = "#26292f", fg = "#9ca3b2"},
    DiffviewStatusModified = {fg = "#fefefe"},
    DiffviewStatusRenamed = {fg = "#fefefe"},
    DiffviewStatusTypeChange = {fg = "#fefefe"},
    DiffviewStatusUnknown = {fg = "#ffffff"},
    DiffviewStatusUnmerged = {fg = "#fefefe"},
    DiffviewStatusUntracked = {fg = "#3dd177"},
    DiffviewWinSeparator = {fg = "#b0bec4"},
    Directory = {fg = "#00b0ff"},
    EndOfBuffer = {link = "NonText"},
    Error = {fg = "#d54e53"},
    ErrorMsg = {fg = "#d54e53"},
    Exception = {link = "Statement"},
    FlashBackdrop = {link = "Comment"},
    FlashCurrent = {link = "IncSearch"},
    FlashLabel = {fg = "#ff008c"},
    FlashMatch = {link = "Search"},
    Float = {fg = "#c678dd"},
    FloatBorder = {link = "WinSeparator"},
    FloatShadow = {bg = "#000000", blend = 80},
    FloatShadowThrough = {bg = "#000000", blend = 100},
    FloatTitle = {fg = "#ffffff"},
    FoldColumn = {bg = "#26292f"},
    Folded = {bg = "#26292f", fg = "#676e7b"},
    Function = {fg = "#3dd177"},
    GitConflictCurrent = {bg = "#286557"},
    GitConflictCurrentLabel = {fg = "#fefefe"},
    GitConflictIncoming = {bg = "#185430"},
    GitConflictIncomingLabel = {fg = "#fefefe"},
    Identifier = {fg = "#ffffff"},
    Ignore = {fg = "#ffc900"},
    IlluminatedWordRead = {link = "LspReferenceRead"},
    IlluminatedWordText = {link = "LspReferenceText"},
    IlluminatedWordWrite = {link = "LspReferenceWrite"},
    IncSearch = {reverse = true},
    Include = {fg = "#ffffff"},
    IndentBlanklineIndent1 = {fg = "#ffffff", nocombine = true},
    IndentBlanklineIndent2 = {fg = "#ffc900", nocombine = true},
    IndentBlanklineIndent3 = {fg = "#3dd177", nocombine = true},
    IndentBlanklineIndent4 = {fg = "#64fcda", nocombine = true},
    IndentBlanklineIndent5 = {fg = "#00b0ff", nocombine = true},
    IndentBlanklineIndent6 = {fg = "#c678dd", nocombine = true},
    Keyword = {fg = "#82f4a2"},
    Label = {fg = "#ffffff"},
    LazyButton = {bg = "#383a3e", fg = "#fefefe"},
    LazyButtonActive = {bg = "#fefefe", fg = "#1e2024"},
    LazyComment = {link = "Comment"},
    LazyCommit = {fg = "#3dd177"},
    LazyCommitIssue = {link = "Number"},
    LazyCommitScope = {},
    LazyCommitType = {bold = true, fg = "#ffc900"},
    LazyDimmed = {link = "Comment"},
    LazyDir = {fg = "#ffc900"},
    LazyH1 = {bg = "#fefefe", fg = "#1e2024"},
    LazyH2 = {bold = true, fg = "#fefefe"},
    LazyNoCond = {link = "DiagnosticWarn"},
    LazyNormal = {link = "NormalFloat"},
    LazyProgressDone = {fg = "#3dd177"},
    LazyProgressTodo = {fg = "#9ca3b2"},
    LazyProp = {fg = "#676e7b"},
    LazyReasonCmd = {fg = "#3dd177"},
    LazyReasonEvent = {fg = "#ffc900"},
    LazyReasonFt = {fg = "#d19a66"},
    LazyReasonImport = {fg = "#ffffff"},
    LazyReasonKeys = {fg = "#64fcda"},
    LazyReasonPlugin = {fg = "#c678dd"},
    LazyReasonRuntime = {fg = "#64fcda"},
    LazyReasonSource = {fg = "#00b0ff"},
    LazyReasonStart = {fg = "#3dd177"},
    LazySpecial = {fg = "#ffffff"},
    LazyTaskError = {link = "ErrorMsg"},
    LazyTaskOutput = {link = "MsgArea"},
    LazyUrl = {fg = "#00b0ff", undercurl = true},
    LazyValue = {fg = "#b0bec4"},
    LeapBackdrop = {fg = "#676e7b"},
    LeapLabelPrimary = {fg = "#ff008c"},
    LeapLabelSecondary = {fg = "#2b8db3"},
    LeapMatch = {fg = "#ff008c", underline = true},
    LineNr = {fg = "#313244"},
    LineNrAbove = {link = "LineNr"},
    LineNrBelow = {link = "LineNr"},
    LspInfoBorder = {link = "FloatBorder"},
    LspInfoFiletype = {fg = "#fefefe"},
    LspInfoList = {fg = "#00b0ff"},
    LspInfoTip = {link = "Comment"},
    LspInfoTitle = {fg = "#64fcda"},
    LspInlayHint = {link = "Comment"},
    LspReferenceRead = {bg = "#383a3e", bold = true},
    LspReferenceText = {bg = "#383a3e", bold = true},
    LspReferenceWrite = {bg = "#383a3e", bold = true},
    Macro = {fg = "#3dd177"},
    MasonError = {fg = "#d54e53"},
    MasonHeader = {bg = "#64fcda", bold = true, fg = "#2d2e27"},
    MasonHeaderSecondary = {bg = "#ffc900", bold = true, fg = "#2d2e27"},
    MasonHeading = {bold = true, fg = "#fefefe"},
    MasonHighlight = {fg = "#00b0ff"},
    MasonHighlightBlock = {bg = "#64fcda", fg = "#26292f"},
    MasonHighlightBlockBold = {bg = "#64fcda", bold = true, fg = "#26292f"},
    MasonHighlightBlockBoldSecondary = {
        bg = "#ffc900",
        bold = true,
        fg = "#26292f"
    },
    MasonHighlightBlockSecondary = {bg = "#ffc900", fg = "#26292f"},
    MasonHighlightSecondary = {fg = "#ffc900"},
    MasonLink = {fg = "#00b0ff"},
    MasonMuted = {fg = "#ffffff"},
    MasonMutedBlock = {bg = "#9ca3b2", fg = "#26292f"},
    MasonMutedBlockBold = {bg = "#9ca3b2", bold = true, fg = "#26292f"},
    MatchParen = {bg = "#313244", bold = true},
    Method = {},
    MiniCursorword = {underline = true},
    MiniCursorwordCurrent = {underline = true},
    MiniStatuslineDevinfo = {link = "StatusLine"},
    MiniStatuslineFileinfo = {link = "StatusLine"},
    MiniStatuslineFilename = {link = "StatusLineNC"},
    MiniStatuslineInactive = {link = "StatusLineNC"},
    MiniStatuslineModeCommand = {link = "DiffText"},
    MiniStatuslineModeInsert = {link = "DiffChange"},
    MiniStatuslineModeNormal = {link = "Cursor"},
    MiniStatuslineModeOther = {link = "IncSearch"},
    MiniStatuslineModeReplace = {link = "DiffDelete"},
    MiniStatuslineModeVisual = {link = "DiffAdd"},
    MiniTablineCurrent = {link = "TabLineSel"},
    MiniTablineFill = {link = "Normal"},
    MiniTablineHidden = {link = "TabLine"},
    MiniTablineModifiedCurrent = {link = "StatusLine"},
    MiniTablineModifiedHidden = {link = "StatusLineNC"},
    MiniTablineModifiedVisible = {link = "StatusLine"},
    MiniTablineTabpagesection = {link = "Search"},
    MiniTablineVisible = {link = "TabLineSel"},
    ModeMsg = {fg = "#ffc900"},
    MoreMsg = {fg = "#ffc900"},
    MsgArea = {},
    MsgSeparator = {link = "StatusLine"},
    NONE = {},
    NavicIconsArray = {link = "Type"},
    NavicIconsBoolean = {link = "Boolean"},
    NavicIconsClass = {link = "CmpItemKindClass"},
    NavicIconsConstant = {link = "CmpItemKindConstant"},
    NavicIconsConstructor = {link = "CmpItemKindConstructor"},
    NavicIconsEnum = {link = "CmpItemKindEnum"},
    NavicIconsEnumMember = {link = "CmpItemKindEnumMember"},
    NavicIconsEvent = {link = "CmpItemKindEvent"},
    NavicIconsField = {link = "CmpItemKindField"},
    NavicIconsFile = {link = "CmpItemKindFile"},
    NavicIconsFunction = {link = "CmpItemKindFunction"},
    NavicIconsInterface = {link = "CmpItemKindInterface"},
    NavicIconsKey = {link = "CmpItemKindValue"},
    NavicIconsMethod = {link = "CmpItemKindMethod"},
    NavicIconsModule = {link = "CmpItemKindModule"},
    NavicIconsNamespace = {link = "CmpItemKindModule"},
    NavicIconsNull = {link = "Constant"},
    NavicIconsNumber = {link = "Number"},
    NavicIconsObject = {link = "CmpItemKindProperty"},
    NavicIconsOperator = {link = "CmpItemKindOperator"},
    NavicIconsPackage = {link = "CmpItemKindModule"},
    NavicIconsProperty = {link = "CmpItemKindProperty"},
    NavicIconsString = {link = "String"},
    NavicIconsStruct = {link = "CmpItemKindStruct"},
    NavicIconsTypeParameter = {link = "CmpItemKindTypeParameter"},
    NavicIconsVariable = {link = "CmpItemKindVariable"},
    NavicSeparator = {fg = "#00b0ff"},
    NavicText = {link = "Normal"},
    NeoTreeBufferNumber = {link = "SpecialChar"},
    NeoTreeCursorLine = {link = "CursorLine"},
    NeoTreeDimText = {fg = "#505050"},
    NeoTreeDirectoryIcon = {link = "Directory"},
    NeoTreeDirectoryName = {link = "Directory"},
    NeoTreeDotfile = {fg = "#626262"},
    NeoTreeEndOfBuffer = {link = "EndOfBuffer"},
    NeoTreeExpander = {link = "NeoTreeDimText"},
    NeoTreeFadeText1 = {fg = "#626262"},
    NeoTreeFadeText2 = {fg = "#444444"},
    NeoTreeFileIcon = {link = "NeoTreeDirectoryIcon"},
    NeoTreeFileName = {},
    NeoTreeFileNameOpened = {bold = true},
    NeoTreeFilterTerm = {link = "SpecialChar"},
    NeoTreeFloatBorder = {link = "FloatBorder"},
    NeoTreeFloatNormal = {link = "NormalFloat"},
    NeoTreeFloatTitle = {fg = "#b0bec4"},
    NeoTreeGitAdded = {fg = "#5faf5f"},
    NeoTreeGitConflict = {bold = true, fg = "#ff8700", italic = true},
    NeoTreeGitDeleted = {fg = "#ff5900"},
    NeoTreeGitIgnored = {link = "NeoTreeDotfile"},
    NeoTreeGitModified = {fg = "#d7af5f"},
    NeoTreeGitRenamed = {link = "NeoTreeGitModified"},
    NeoTreeGitStaged = {link = "NeoTreeGitAdded"},
    NeoTreeGitUnstaged = {link = "NeoTreeGitConflict"},
    NeoTreeGitUntracked = {fg = "#ff8700", italic = true},
    NeoTreeHiddenByName = {link = "NeoTreeDotfile"},
    NeoTreeIndentMarker = {link = "NeoTreeDimText"},
    NeoTreeMessage = {fg = "#505050", italic = true},
    NeoTreeModified = {fg = "#d7d787"},
    NeoTreeNormal = {link = "Normal"},
    NeoTreeNormalNC = {link = "NormalNC"},
    NeoTreePreview = {link = "Search"},
    NeoTreeRootName = {bold = true, italic = true},
    NeoTreeSignColumn = {link = "SignColumn"},
    NeoTreeStatusLine = {link = "StatusLine"},
    NeoTreeStatusLineNC = {link = "StatusLineNC"},
    NeoTreeSymbolicLinkTarget = {link = "NeoTreeFileName"},
    NeoTreeTabActive = {bold = true},
    NeoTreeTabInactive = {bg = "#141414", fg = "#777777"},
    NeoTreeTabSeparatorActive = {fg = "#0a0a0a"},
    NeoTreeTabSeparatorInactive = {bg = "#141414", fg = "#101010"},
    NeoTreeTitleBar = {bg = "#b0bec4"},
    NeoTreeVertSplit = {link = "VertSplit"},
    NeoTreeWinSeparator = {link = "WinSeparator"},
    NeoTreeWindowsHidden = {link = "NeoTreeDotfile"},
    NeogitBranch = {bold = true, fg = "#ffffff"},
    NeogitChangeAdded = {bold = true, fg = "#d1bb67", italic = true},
    NeogitChangeBothModified = {bold = true, fg = "#33ad63", italic = true},
    NeogitChangeCopied = {bold = true, fg = "#d1d1d1", italic = true},
    NeogitChangeDeleted = {bold = true, fg = "#af4044", italic = true},
    NeogitChangeModified = {bold = true, fg = "#32ab62", italic = true},
    NeogitChangeNewFile = {bold = true, fg = "#d1bb67", italic = true},
    NeogitChangeRenamed = {bold = true, fg = "#d1d1d1", italic = true},
    NeogitChangeUpdated = {bold = true, fg = "#d4d4d4", italic = true},
    NeogitCommandCodeError = {link = "Error"},
    NeogitCommandCodeNormal = {link = "String"},
    NeogitCommandText = {link = "Comment"},
    NeogitCommandTime = {link = "Comment"},
    NeogitCommitViewHeader = {bg = "#d1d1d1", fg = "#22252a"},
    NeogitCursorLine = {bg = "#26292e"},
    NeogitDiffAdd = {bg = "#123f24", fg = "#d1bb67"},
    NeogitDiffAddHighlight = {bg = "#123f24", fg = "#ffe47e"},
    NeogitDiffContext = {bg = "#26292e"},
    NeogitDiffContextHighlight = {bg = "#303338"},
    NeogitDiffDelete = {bg = "#401719", fg = "#af4044"},
    NeogitDiffDeleteHighlight = {bg = "#401719", fg = "#d54e53"},
    NeogitDiffHeader = {bg = "#3a3d41", bold = true, fg = "#3dd177"},
    NeogitDiffHeaderHighlight = {bg = "#3a3d41", bold = true, fg = "#ffffff"},
    NeogitFilePath = {fg = "#3dd177", italic = true},
    NeogitFold = {},
    NeogitGraphBlue = {fg = "#3dd177"},
    NeogitGraphBoldBlue = {bold = true, fg = "#3dd177"},
    NeogitGraphBoldCyan = {bold = true, fg = "#ffffff"},
    NeogitGraphBoldGray = {bold = true, fg = "#7a7c7f"},
    NeogitGraphBoldGreen = {bold = true, fg = "#ffe47e"},
    NeogitGraphBoldOrange = {bold = true, fg = "#ffffff"},
    NeogitGraphBoldPurple = {bold = true, fg = "#ffffff"},
    NeogitGraphBoldRed = {bold = true, fg = "#d54e53"},
    NeogitGraphBoldWhite = {bold = true},
    NeogitGraphBoldYellow = {bold = true, fg = "#3dd177"},
    NeogitGraphCyan = {fg = "#ffffff"},
    NeogitGraphGray = {fg = "#7a7c7f"},
    NeogitGraphGreen = {fg = "#ffe47e"},
    NeogitGraphOrange = {fg = "#ffffff"},
    NeogitGraphPurple = {fg = "#ffffff"},
    NeogitGraphRed = {fg = "#d54e53"},
    NeogitGraphWhite = {},
    NeogitGraphYellow = {fg = "#3dd177"},
    NeogitHunkHeader = {bg = "#7a7c7f", bold = true, fg = "#22252a"},
    NeogitHunkHeaderHighlight = {bg = "#ffffff", bold = true, fg = "#22252a"},
    NeogitNotificationError = {link = "DiagnosticError"},
    NeogitNotificationInfo = {link = "DiagnosticInfo"},
    NeogitNotificationWarning = {link = "DiagnosticWarn"},
    NeogitObjectId = {link = "Comment"},
    NeogitPopupActionDisabled = {link = "Comment"},
    NeogitPopupActionKey = {fg = "#ffffff"},
    NeogitPopupBold = {bold = true},
    NeogitPopupBranchName = {link = "String"},
    NeogitPopupConfigDisabled = {link = "Comment"},
    NeogitPopupConfigEnabled = {link = "SpecialChar"},
    NeogitPopupConfigKey = {fg = "#ffffff"},
    NeogitPopupOptionDisabled = {link = "Comment"},
    NeogitPopupOptionEnabled = {link = "SpecialChar"},
    NeogitPopupOptionKey = {fg = "#ffffff"},
    NeogitPopupSectionTitle = {link = "Function"},
    NeogitPopupSwitchDisabled = {link = "Comment"},
    NeogitPopupSwitchEnabled = {link = "SpecialChar"},
    NeogitPopupSwitchKey = {fg = "#ffffff"},
    NeogitRebaseDone = {link = "Comment"},
    NeogitRebasing = {bold = true, fg = "#d1d1d1"},
    NeogitRecentcommits = {bold = true, fg = "#d1d1d1"},
    NeogitRemote = {bold = true, fg = "#ffe47e"},
    NeogitStagedchanges = {bold = true, fg = "#d1d1d1"},
    NeogitStash = {link = "Comment"},
    NeogitStashes = {bold = true, fg = "#d1d1d1"},
    NeogitUnmergedInto = {bold = true, fg = "#d1d1d1"},
    NeogitUnmergedchanges = {bold = true, fg = "#d1d1d1"},
    NeogitUnpulledFrom = {bold = true, fg = "#d1d1d1"},
    NeogitUnpulledchanges = {bold = true, fg = "#d1d1d1"},
    NeogitUnpushedTo = {bold = true, fg = "#d1d1d1"},
    NeogitUnstagedchanges = {bold = true, fg = "#d1d1d1"},
    NeogitUntrackedfiles = {bold = true, fg = "#d1d1d1"},
    NeoscrollHiddenCursor = {blend = 100, reverse = true},
    Noise = {},
    NonText = {fg = "#313244"},
    Normal = {fg = "#b0bec4"},
    NormalFloat = {link = "Pmenu"},
    NormalNC = {},
    NotifyBackground = {link = "Normal"},
    NotifyDEBUGBody = {fg = "#b0bec4"},
    NotifyDEBUGBorder = {fg = "#c678dd"},
    NotifyDEBUGIcon = {fg = "#c678dd"},
    NotifyDEBUGTitle = {fg = "#c678dd"},
    NotifyERRORBody = {fg = "#b0bec4"},
    NotifyERRORBorder = {fg = "#d54e53"},
    NotifyERRORIcon = {fg = "#d54e53"},
    NotifyERRORTitle = {fg = "#d54e53"},
    NotifyINFOBody = {fg = "#b0bec4"},
    NotifyINFOBorder = {fg = "#3dd177"},
    NotifyINFOIcon = {fg = "#3dd177"},
    NotifyINFOTitle = {fg = "#3dd177"},
    NotifyLogTime = {link = "Comment"},
    NotifyLogTitle = {link = "Special"},
    NotifyTRACEBody = {fg = "#b0bec4"},
    NotifyTRACEBorder = {fg = "#fefefe"},
    NotifyTRACEIcon = {fg = "#fefefe"},
    NotifyTRACETitle = {fg = "#fefefe"},
    NotifyWARNBody = {fg = "#b0bec4"},
    NotifyWARNBorder = {fg = "#ffc900"},
    NotifyWARNIcon = {fg = "#ffc900"},
    NotifyWARNTitle = {fg = "#ffc900"},
    Number = {fg = "#c678dd"},
    NvimAnd = {link = "NvimBinaryOperator"},
    NvimArrow = {link = "Delimiter"},
    NvimAssignment = {link = "Operator"},
    NvimAssignmentWithAddition = {link = "NvimAugmentedAssignment"},
    NvimAssignmentWithConcatenation = {link = "NvimAugmentedAssignment"},
    NvimAssignmentWithSubtraction = {link = "NvimAugmentedAssignment"},
    NvimAugmentedAssignment = {link = "NvimAssignment"},
    NvimBinaryMinus = {link = "NvimBinaryOperator"},
    NvimBinaryOperator = {link = "NvimOperator"},
    NvimBinaryPlus = {link = "NvimBinaryOperator"},
    NvimCallingParenthesis = {link = "NvimParenthesis"},
    NvimColon = {link = "Delimiter"},
    NvimComma = {link = "Delimiter"},
    NvimComparison = {link = "NvimBinaryOperator"},
    NvimComparisonModifier = {link = "NvimComparison"},
    NvimConcat = {link = "NvimBinaryOperator"},
    NvimConcatOrSubscript = {link = "NvimConcat"},
    NvimContainer = {link = "NvimParenthesis"},
    NvimCurly = {link = "NvimSubscript"},
    NvimDict = {link = "NvimContainer"},
    NvimDivision = {link = "NvimBinaryOperator"},
    NvimDoubleQuote = {link = "NvimStringQuote"},
    NvimDoubleQuotedBody = {link = "NvimStringBody"},
    NvimDoubleQuotedEscape = {link = "NvimStringSpecial"},
    NvimDoubleQuotedUnknownEscape = {link = "NvimInvalidValue"},
    NvimEnvironmentName = {link = "NvimIdentifier"},
    NvimEnvironmentSigil = {link = "NvimOptionSigil"},
    NvimFigureBrace = {link = "NvimInternalError"},
    NvimFloat = {link = "NvimNumber"},
    NvimIdentifier = {link = "Identifier"},
    NvimIdentifierKey = {link = "NvimIdentifier"},
    NvimIdentifierName = {link = "NvimIdentifier"},
    NvimIdentifierScope = {link = "NvimIdentifier"},
    NvimIdentifierScopeDelimiter = {link = "NvimIdentifier"},
    NvimInternalError = {
        bg = "#ff0000",
        ctermbg = 9,
        ctermfg = 9,
        fg = "#ff0000"
    },
    NvimInvalid = {link = "Error"},
    NvimInvalidAnd = {link = "NvimInvalidBinaryOperator"},
    NvimInvalidArrow = {link = "NvimInvalidDelimiter"},
    NvimInvalidAssignment = {link = "NvimInvalid"},
    NvimInvalidAssignmentWithAddition = {
        link = "NvimInvalidAugmentedAssignment"
    },
    NvimInvalidAssignmentWithConcatenation = {
        link = "NvimInvalidAugmentedAssignment"
    },
    NvimInvalidAssignmentWithSubtraction = {
        link = "NvimInvalidAugmentedAssignment"
    },
    NvimInvalidAugmentedAssignment = {link = "NvimInvalidAssignment"},
    NvimInvalidBinaryMinus = {link = "NvimInvalidBinaryOperator"},
    NvimInvalidBinaryOperator = {link = "NvimInvalidOperator"},
    NvimInvalidBinaryPlus = {link = "NvimInvalidBinaryOperator"},
    NvimInvalidCallingParenthesis = {link = "NvimInvalidParenthesis"},
    NvimInvalidColon = {link = "NvimInvalidDelimiter"},
    NvimInvalidComma = {link = "NvimInvalidDelimiter"},
    NvimInvalidComparison = {link = "NvimInvalidBinaryOperator"},
    NvimInvalidComparisonModifier = {link = "NvimInvalidComparison"},
    NvimInvalidConcat = {link = "NvimInvalidBinaryOperator"},
    NvimInvalidConcatOrSubscript = {link = "NvimInvalidConcat"},
    NvimInvalidContainer = {link = "NvimInvalidParenthesis"},
    NvimInvalidCurly = {link = "NvimInvalidSubscript"},
    NvimInvalidDelimiter = {link = "NvimInvalid"},
    NvimInvalidDict = {link = "NvimInvalidContainer"},
    NvimInvalidDivision = {link = "NvimInvalidBinaryOperator"},
    NvimInvalidDoubleQuote = {link = "NvimInvalidStringQuote"},
    NvimInvalidDoubleQuotedBody = {link = "NvimInvalidStringBody"},
    NvimInvalidDoubleQuotedEscape = {link = "NvimInvalidStringSpecial"},
    NvimInvalidDoubleQuotedUnknownEscape = {link = "NvimInvalidValue"},
    NvimInvalidEnvironmentName = {link = "NvimInvalidIdentifier"},
    NvimInvalidEnvironmentSigil = {link = "NvimInvalidOptionSigil"},
    NvimInvalidFigureBrace = {link = "NvimInvalidDelimiter"},
    NvimInvalidFloat = {link = "NvimInvalidNumber"},
    NvimInvalidIdentifier = {link = "NvimInvalidValue"},
    NvimInvalidIdentifierKey = {link = "NvimInvalidIdentifier"},
    NvimInvalidIdentifierName = {link = "NvimInvalidIdentifier"},
    NvimInvalidIdentifierScope = {link = "NvimInvalidIdentifier"},
    NvimInvalidIdentifierScopeDelimiter = {link = "NvimInvalidIdentifier"},
    NvimInvalidLambda = {link = "NvimInvalidParenthesis"},
    NvimInvalidList = {link = "NvimInvalidContainer"},
    NvimInvalidMod = {link = "NvimInvalidBinaryOperator"},
    NvimInvalidMultiplication = {link = "NvimInvalidBinaryOperator"},
    NvimInvalidNestingParenthesis = {link = "NvimInvalidParenthesis"},
    NvimInvalidNot = {link = "NvimInvalidUnaryOperator"},
    NvimInvalidNumber = {link = "NvimInvalidValue"},
    NvimInvalidNumberPrefix = {link = "NvimInvalidNumber"},
    NvimInvalidOperator = {link = "NvimInvalid"},
    NvimInvalidOptionName = {link = "NvimInvalidIdentifier"},
    NvimInvalidOptionScope = {link = "NvimInvalidIdentifierScope"},
    NvimInvalidOptionScopeDelimiter = {
        link = "NvimInvalidIdentifierScopeDelimiter"
    },
    NvimInvalidOptionSigil = {link = "NvimInvalidIdentifier"},
    NvimInvalidOr = {link = "NvimInvalidBinaryOperator"},
    NvimInvalidParenthesis = {link = "NvimInvalidDelimiter"},
    NvimInvalidPlainAssignment = {link = "NvimInvalidAssignment"},
    NvimInvalidRegister = {link = "NvimInvalidValue"},
    NvimInvalidSingleQuote = {link = "NvimInvalidStringQuote"},
    NvimInvalidSingleQuotedBody = {link = "NvimInvalidStringBody"},
    NvimInvalidSingleQuotedQuote = {link = "NvimInvalidStringSpecial"},
    NvimInvalidSingleQuotedUnknownEscape = {link = "NvimInternalError"},
    NvimInvalidSpacing = {link = "ErrorMsg"},
    NvimInvalidString = {link = "NvimInvalidValue"},
    NvimInvalidStringBody = {link = "NvimStringBody"},
    NvimInvalidStringQuote = {link = "NvimInvalidString"},
    NvimInvalidStringSpecial = {link = "NvimStringSpecial"},
    NvimInvalidSubscript = {link = "NvimInvalidParenthesis"},
    NvimInvalidSubscriptBracket = {link = "NvimInvalidSubscript"},
    NvimInvalidSubscriptColon = {link = "NvimInvalidSubscript"},
    NvimInvalidTernary = {link = "NvimInvalidOperator"},
    NvimInvalidTernaryColon = {link = "NvimInvalidTernary"},
    NvimInvalidUnaryMinus = {link = "NvimInvalidUnaryOperator"},
    NvimInvalidUnaryOperator = {link = "NvimInvalidOperator"},
    NvimInvalidUnaryPlus = {link = "NvimInvalidUnaryOperator"},
    NvimInvalidValue = {link = "NvimInvalid"},
    NvimLambda = {link = "NvimParenthesis"},
    NvimList = {link = "NvimContainer"},
    NvimMod = {link = "NvimBinaryOperator"},
    NvimMultiplication = {link = "NvimBinaryOperator"},
    NvimNestingParenthesis = {link = "NvimParenthesis"},
    NvimNot = {link = "NvimUnaryOperator"},
    NvimNumber = {link = "Number"},
    NvimNumberPrefix = {link = "Type"},
    NvimOperator = {link = "Operator"},
    NvimOptionName = {link = "NvimIdentifier"},
    NvimOptionScope = {link = "NvimIdentifierScope"},
    NvimOptionScopeDelimiter = {link = "NvimIdentifierScopeDelimiter"},
    NvimOptionSigil = {link = "Type"},
    NvimOr = {link = "NvimBinaryOperator"},
    NvimParenthesis = {link = "Delimiter"},
    NvimPlainAssignment = {link = "NvimAssignment"},
    NvimRegister = {link = "SpecialChar"},
    NvimSingleQuote = {link = "NvimStringQuote"},
    NvimSingleQuotedBody = {link = "NvimStringBody"},
    NvimSingleQuotedQuote = {link = "NvimStringSpecial"},
    NvimSingleQuotedUnknownEscape = {link = "NvimInternalError"},
    NvimSpacing = {link = "Normal"},
    NvimString = {link = "String"},
    NvimStringBody = {link = "NvimString"},
    NvimStringQuote = {link = "NvimString"},
    NvimStringSpecial = {link = "SpecialChar"},
    NvimSubscript = {link = "NvimParenthesis"},
    NvimSubscriptBracket = {link = "NvimSubscript"},
    NvimSubscriptColon = {link = "NvimSubscript"},
    NvimTernary = {link = "NvimOperator"},
    NvimTernaryColon = {link = "NvimTernary"},
    NvimTreeBookmark = {fg = "#ffc900"},
    NvimTreeEmptyFolderName = {link = "Directory"},
    NvimTreeExecFile = {bold = true, fg = "#ffe47e"},
    NvimTreeFolderIcon = {fg = "#ffc900"},
    NvimTreeFolderName = {link = "Directory"},
    NvimTreeGitDeleted = {fg = "#d54e53"},
    NvimTreeGitDirty = {fg = "#ffffff"},
    NvimTreeGitIgnored = {link = "Comment"},
    NvimTreeGitMerge = {fg = "#c678dd"},
    NvimTreeGitNew = {fg = "#3dd177"},
    NvimTreeGitRenamed = {fg = "#ffffff"},
    NvimTreeGitStaged = {fg = "#3dd177"},
    NvimTreeImageFile = {bold = true, fg = "#c678dd"},
    NvimTreeIndentMarker = {fg = "#9ca3b2"},
    NvimTreeLiveFilterPrefix = {bold = true, fg = "#ffffff"},
    NvimTreeLiveFilterValue = {bold = true},
    NvimTreeOpenedFile = {bold = true, fg = "#ffc900"},
    NvimTreeOpenedFolderName = {link = "Directory"},
    NvimTreeRootFolder = {fg = "#ffffff"},
    NvimTreeSpecialFile = {bold = true, fg = "#3dd177", underline = true},
    NvimTreeSymlink = {bold = true, fg = "#ffffff"},
    NvimTreeWindowPicker = {bg = "#00b0ff", bold = true, fg = "#fefefe"},
    NvimUnaryMinus = {link = "NvimUnaryOperator"},
    NvimUnaryOperator = {link = "NvimOperator"},
    NvimUnaryPlus = {link = "NvimUnaryOperator"},
    Operator = {fg = "#ffffff"},
    Pmenu = {fg = "#b0bec4"},
    PmenuExtra = {link = "Pmenu"},
    PmenuExtraSel = {link = "PmenuSel"},
    PmenuKind = {link = "Pmenu"},
    PmenuKindSel = {link = "PmenuSel"},
    PmenuSbar = {bg = "#808080", ctermbg = 248},
    PmenuSel = {bg = "#ffffff", fg = "#18191a"},
    PmenuThumb = {bg = "#313244", fg = "#2d2e27"},
    PreCondit = {fg = "#ffffff"},
    PreProc = {fg = "#3dd177"},
    Question = {fg = "#ffc900"},
    QuickFixLine = {link = "Search"},
    RedrawDebugClear = {bg = "#ffff00", ctermbg = 11},
    RedrawDebugComposed = {bg = "#008000", ctermbg = 10},
    RedrawDebugNormal = {reverse = true},
    RedrawDebugRecompose = {bg = "#ff0000", ctermbg = 9},
    Repeat = {link = "Statement"},
    Search = {bg = "#ffc900", fg = "#18191a"},
    SignColumn = {},
    SjLabel = {fg = "#ff008c"},
    SjLimit = {link = "ErrorMsg"},
    SjOverlay = {link = "Comment"},
    SjSearch = {link = "IncSearch"},
    SjWarning = {link = "WarningMsg"},
    Special = {fg = "#c678dd"},
    SpecialChar = {fg = "#ffffff"},
    SpecialComment = {fg = "#64fcda"},
    SpecialKey = {fg = "#ffffff"},
    SpellBad = {ctermbg = 9, sp = "#ff0000", undercurl = true},
    SpellCap = {ctermbg = 12, sp = "#0000ff", undercurl = true},
    SpellLocal = {ctermbg = 14, sp = "#00ffff", undercurl = true},
    SpellRare = {ctermbg = 13, sp = "#ff00ff", undercurl = true},
    Statement = {fg = "#ffffff"},
    StatusLine = {bg = "#1e2024", fg = "#9ca3b2"},
    StatusLineNC = {bg = "#26292f", fg = "#9ca3b2"},
    StorageClass = {fg = "#64fcda"},
    String = {fg = "#ffe47e"},
    Struct = {},
    Structure = {fg = "#64fcda"},
    Substitute = {link = "Search"},
    TSPlaygroundFocus = {link = "Visual"},
    TSPlaygroundLang = {link = "String"},
    TSQueryLinterError = {link = "Error"},
    TSRainbowBlue = {fg = "#00b0ff"},
    TSRainbowCyan = {fg = "#64fcda"},
    TSRainbowGreen = {fg = "#3dd177"},
    TSRainbowOrange = {fg = "#d19a66"},
    TSRainbowRed = {fg = "#d03770"},
    TSRainbowViolet = {fg = "#c678dd"},
    TSRainbowYellow = {fg = "#ffc900"},
    TabLine = {bg = "#26292f", fg = "#b0bec4", reverse = true},
    TabLineFill = {reverse = true},
    TabLineSel = {bold = true},
    Tag = {fg = "#ffffff"},
    TelescopeBorder = {link = "FloatBorder"},
    TelescopeMatching = {link = "Special"},
    TelescopeMultiIcon = {link = "Identifier"},
    TelescopeMultiSelection = {link = "Type"},
    TelescopeNormal = {link = "Normal"},
    TelescopePreviewBlock = {link = "Constant"},
    TelescopePreviewBorder = {link = "TelescopeBorder"},
    TelescopePreviewCharDev = {link = "Constant"},
    TelescopePreviewDate = {link = "Directory"},
    TelescopePreviewDirectory = {link = "Directory"},
    TelescopePreviewExecute = {link = "String"},
    TelescopePreviewGroup = {link = "Constant"},
    TelescopePreviewHyphen = {link = "NonText"},
    TelescopePreviewLine = {link = "Visual"},
    TelescopePreviewLink = {link = "Special"},
    TelescopePreviewMatch = {link = "Search"},
    TelescopePreviewMessage = {link = "TelescopePreviewNormal"},
    TelescopePreviewMessageFillchar = {link = "TelescopePreviewMessage"},
    TelescopePreviewNormal = {link = "TelescopeNormal"},
    TelescopePreviewPipe = {link = "Constant"},
    TelescopePreviewRead = {link = "Constant"},
    TelescopePreviewSize = {link = "String"},
    TelescopePreviewSocket = {link = "Statement"},
    TelescopePreviewSticky = {link = "Keyword"},
    TelescopePreviewTitle = {link = "TelescopeTitle"},
    TelescopePreviewUser = {link = "Constant"},
    TelescopePreviewWrite = {link = "Statement"},
    TelescopePromptBorder = {link = "TelescopeBorder"},
    TelescopePromptCounter = {fg = "#00b0ff"},
    TelescopePromptNormal = {link = "TelescopeNormal"},
    TelescopePromptPrefix = {link = "Identifier"},
    TelescopePromptTitle = {link = "TelescopeTitle"},
    TelescopeResultsBorder = {link = "TelescopeBorder"},
    TelescopeResultsClass = {link = "Function"},
    TelescopeResultsComment = {link = "Comment"},
    TelescopeResultsConstant = {link = "Constant"},
    TelescopeResultsDiffAdd = {link = "DiffAdd"},
    TelescopeResultsDiffChange = {link = "DiffChange"},
    TelescopeResultsDiffDelete = {link = "DiffDelete"},
    TelescopeResultsDiffUntracked = {link = "NonText"},
    TelescopeResultsField = {link = "Function"},
    TelescopeResultsFunction = {link = "Function"},
    TelescopeResultsIdentifier = {link = "Identifier"},
    TelescopeResultsLineNr = {link = "LineNr"},
    TelescopeResultsMethod = {link = "Method"},
    TelescopeResultsNormal = {link = "TelescopeNormal"},
    TelescopeResultsNumber = {link = "Number"},
    TelescopeResultsOperator = {link = "Operator"},
    TelescopeResultsSpecialComment = {link = "SpecialComment"},
    TelescopeResultsStruct = {link = "Struct"},
    TelescopeResultsTitle = {link = "TelescopeTitle"},
    TelescopeResultsVariable = {link = "SpecialChar"},
    TelescopeSelection = {link = "Visual"},
    TelescopeSelectionCaret = {link = "TelescopeSelection"},
    TelescopeTitle = {fg = "#00b0ff"},
    TermCursor = {reverse = true},
    TermCursorNC = {},
    Title = {fg = "#ffc900"},
    Todo = {bold = true, fg = "#d19a66"},
    TracesCursor = {link = "TracesSearch"},
    TracesReplace = {link = "TracesSearch"},
    TracesSearch = {link = "Search"},
    TreesitterContext = {link = "NormalFloat"},
    TreesitterContextBottom = {link = "NONE"},
    TreesitterContextLineNumber = {link = "LineNr"},
    TreesitterContextSeparator = {link = "FloatBorder"},
    TroubleCode = {link = "Comment"},
    TroubleCount = {link = "TabLineSel"},
    TroubleError = {link = "DiagnosticError"},
    TroubleFile = {link = "Directory"},
    TroubleFoldIcon = {link = "CursorLineNr"},
    TroubleHint = {link = "DiagnosticHint"},
    TroubleIndent = {link = "LineNr"},
    TroubleInformation = {link = "DiagnosticInfo"},
    TroubleLocation = {link = "LineNr"},
    TroubleNormal = {link = "Normal"},
    TroubleOther = {link = "DiagnosticOther"},
    TroublePreview = {link = "Search"},
    TroubleSignError = {link = "DiagnosticSignError"},
    TroubleSignHint = {link = "DiagnosticSignHint"},
    TroubleSignInformation = {link = "DiagnosticSignInfo"},
    TroubleSignOther = {link = "TroubleSignInformation"},
    TroubleSignWarning = {link = "DiagnosticSignWarn"},
    TroubleSource = {link = "Comment"},
    TroubleText = {link = "Normal"},
    TroubleTextError = {link = "TroubleText"},
    TroubleTextHint = {link = "TroubleText"},
    TroubleTextInformation = {link = "TroubleText"},
    TroubleTextWarning = {link = "TroubleText"},
    TroubleWarning = {link = "DiagnosticWarn"},
    Type = {fg = "#00b0ff"},
    Typedef = {fg = "#00b0ff"},
    Underlined = {fg = "#3dd177", underline = true},
    VertSplit = {fg = "#b0bec4"},
    Visual = {bg = "#313244"},
    VisualNC = {},
    WarningMsg = {fg = "#ffc900"},
    WhichKey = {fg = "#ffc900"},
    WhichKeyBorder = {fg = "#b0bec4"},
    WhichKeyDesc = {fg = "#ffffff"},
    WhichKeyFloat = {fg = "#b0bec4"},
    WhichKeyGroup = {fg = "#82f4a2"},
    WhichKeySeparator = {fg = "#ffffff"},
    WhichKeyValue = {fg = "#676e7b"},
    Whitespace = {link = "NonText"},
    WildMenu = {bg = "#ffff00", ctermbg = 11, ctermfg = 0, fg = "#000000"},
    WilderDevicons_DevIconDefault = {fg = "#6d8086"},
    WilderDevicons_DevIconJson = {fg = "#cbcb41"},
    WilderDevicons_DevIconLua = {fg = "#51a0cf"},
    WilderPoppupMenuAccent = {bold = true, fg = "#b0bec4", underline = true},
    WilderPopupMenuSelectedAccent = {
        bg = "#ffffff",
        bold = true,
        fg = "#18191a",
        underline = true
    },
    WilderWildmenuAccent = {
        bg = "#1e2024",
        bold = true,
        fg = "#9ca3b2",
        underline = true
    },
    WilderWildmenuSelectedAccent = {
        bg = "#ffff00",
        bold = true,
        ctermbg = 11,
        ctermfg = 0,
        fg = "#000000",
        underline = true
    },
    WinBar = {bold = true},
    WinBarActive = {fg = "#00b0ff", underline = true},
    WinBarInactive = {fg = "#676e7b"},
    WinBarNC = {link = "WinBar"},
    WinSeparator = {link = "VertSplit"},
    cssAnimationAttr = {link = "cssAttr"},
    cssAnimationProp = {link = "cssProp"},
    cssAtKeyword = {link = "PreProc"},
    cssAtRule = {link = "Include"},
    cssAtRuleLogical = {link = "Statement"},
    cssAttr = {link = "Constant"},
    cssAttrComma = {link = "Special"},
    cssAttrRegion = {},
    cssAttributeSelector = {link = "String"},
    cssAuralAttr = {link = "cssAttr"},
    cssAuralProp = {link = "cssProp"},
    cssBackgroundAttr = {link = "cssAttr"},
    cssBackgroundProp = {link = "cssProp"},
    cssBorderAttr = {link = "cssAttr"},
    cssBorderProp = {link = "cssProp"},
    cssBoxAttr = {link = "cssAttr"},
    cssBoxProp = {link = "cssProp"},
    cssBraceError = {link = "Error"},
    cssBraces = {link = "Function"},
    cssCascadeAttr = {link = "cssAttr"},
    cssCascadeProp = {link = "cssProp"},
    cssClassName = {link = "Function"},
    cssClassNameDot = {link = "Function"},
    cssColor = {link = "Constant"},
    cssColorProp = {link = "cssProp"},
    cssComment = {link = "Comment"},
    cssCommonAttr = {link = "cssAttr"},
    cssContentForPagedMediaAttr = {link = "cssAttr"},
    cssContentForPagedMediaProp = {link = "cssProp"},
    cssCustomProp = {link = "Special"},
    cssDefinition = {},
    cssDeprecated = {link = "Error"},
    cssDimensionAttr = {link = "cssAttr"},
    cssDimensionProp = {link = "cssProp"},
    cssError = {link = "Error"},
    cssFlexibleBoxAttr = {link = "cssAttr"},
    cssFlexibleBoxProp = {link = "cssProp"},
    cssFontAttr = {link = "cssAttr"},
    cssFontDescriptor = {link = "Special"},
    cssFontDescriptorAttr = {link = "cssAttr"},
    cssFontDescriptorProp = {link = "cssProp"},
    cssFontProp = {link = "cssProp"},
    cssFunction = {link = "Constant"},
    cssFunctionComma = {link = "Function"},
    cssFunctionName = {link = "Function"},
    cssGeneratedContentAttr = {link = "cssAttr"},
    cssGeneratedContentProp = {link = "cssProp"},
    cssGradientAttr = {link = "cssAttr"},
    cssGridAttr = {link = "cssAttr"},
    cssGridProp = {link = "cssProp"},
    cssHacks = {link = "Comment"},
    cssHyerlinkAttr = {link = "cssAttr"},
    cssHyerlinkProp = {link = "cssProp"},
    cssIEUIAttr = {link = "cssAttr"},
    cssIEUIProp = {link = "cssProp"},
    cssIdentifier = {link = "Function"},
    cssImportant = {link = "Special"},
    cssInteractAttr = {link = "cssAttr"},
    cssInteractProp = {link = "cssProp"},
    cssKeyFrameProp = {link = "Constant"},
    cssLength = {},
    cssLineboxAttr = {link = "cssAttr"},
    cssLineboxProp = {link = "cssProp"},
    cssListAttr = {link = "cssAttr"},
    cssListProp = {link = "cssProp"},
    cssMarginAttr = {link = "cssAttr"},
    cssMarqueeAttr = {link = "cssAttr"},
    cssMarqueeProp = {link = "cssProp"},
    cssMathGroup = {},
    cssMathParens = {},
    cssMediaAttr = {link = "cssAttr"},
    cssMediaComma = {link = "Normal"},
    cssMediaProp = {link = "cssProp"},
    cssMediaType = {link = "Special"},
    cssMobileTextProp = {link = "cssProp"},
    cssMultiColumnAttr = {link = "cssAttr"},
    cssMultiColumnProp = {link = "cssProp"},
    cssNoise = {link = "Noise"},
    cssObjectAttr = {link = "cssAttr"},
    cssObjectProp = {link = "cssProp"},
    cssPaddingAttr = {link = "cssAttr"},
    cssPageMarginProp = {link = "cssAtKeyword"},
    cssPageProp = {link = "cssProp"},
    cssPagePseudo = {link = "PreProc"},
    cssPagedMediaAttr = {link = "cssAttr"},
    cssPagedMediaProp = {link = "cssProp"},
    cssPositioningAttr = {link = "cssAttr"},
    cssPositioningProp = {link = "cssProp"},
    cssPrintAttr = {link = "cssAttr"},
    cssPrintProp = {link = "cssProp"},
    cssProp = {link = "StorageClass"},
    cssPseudoClass = {},
    cssPseudoClassFn = {},
    cssPseudoClassId = {link = "PreProc"},
    cssPseudoClassLang = {link = "Constant"},
    cssRenderAttr = {link = "cssAttr"},
    cssRenderProp = {link = "cssProp"},
    cssRubyAttr = {link = "cssAttr"},
    cssRubyProp = {link = "cssProp"},
    cssSelectorOp = {link = "Special"},
    cssSelectorOp2 = {link = "Special"},
    cssSpecialCharQ = {},
    cssSpecialCharQQ = {},
    cssSpeechAttr = {link = "cssAttr"},
    cssSpeechProp = {link = "cssProp"},
    cssString = {},
    cssStringQ = {link = "String"},
    cssStringQQ = {link = "String"},
    cssStyle = {},
    cssTableAttr = {link = "cssAttr"},
    cssTableProp = {link = "cssProp"},
    cssTagName = {link = "Statement"},
    cssTextAttr = {link = "cssAttr"},
    cssTextProp = {link = "cssProp"},
    cssTransformAttr = {link = "cssAttr"},
    cssTransformProp = {link = "cssProp"},
    cssTransitionAttr = {link = "cssAttr"},
    cssTransitionProp = {link = "cssProp"},
    cssUIAttr = {link = "cssAttr"},
    cssUIProp = {link = "cssProp"},
    cssURL = {link = "String"},
    cssUnicodeEscape = {link = "Special"},
    cssUnicodeRange = {link = "Constant"},
    cssUnitDecorators = {link = "Number"},
    cssValueAngle = {link = "Number"},
    cssValueFrequency = {link = "Number"},
    cssValueInteger = {link = "Number"},
    cssValueLength = {link = "Number"},
    cssValueNumber = {link = "Number"},
    cssValueTime = {link = "Number"},
    cssVendor = {link = "Comment"},
    debugPC = {},
    diffAdded = {fg = "#3dd177"},
    diffChanged = {fg = "#fefefe"},
    diffFile = {fg = "#fefefe"},
    diffIndexLine = {fg = "#64fcda"},
    diffLine = {fg = "#c678dd"},
    diffRemoved = {fg = "#ffffff"},
    diffSubname = {fg = "#64fcda"},
    dtdAttrDef = {link = "dtdType"},
    dtdAttrType = {link = "dtdType"},
    dtdCard = {link = "dtdFunction"},
    dtdComment = {link = "Comment"},
    dtdConstant = {link = "Constant"},
    dtdEntity = {link = "Statement"},
    dtdEntityPunct = {link = "dtdType"},
    dtdEnum = {link = "dtdConstant"},
    dtdError = {link = "Error"},
    dtdFunction = {link = "Function"},
    dtdParamEntityDPunct = {link = "dtdComment"},
    dtdParamEntityDecl = {link = "dtdType"},
    dtdParamEntityInst = {link = "dtdConstant"},
    dtdParamEntityPunct = {link = "dtdType"},
    dtdString = {link = "dtdConstant"},
    dtdTag = {link = "Normal"},
    dtdTagName = {link = "Statement"},
    dtdTodo = {link = "Todo"},
    dtdType = {link = "Type"},
    healthSuccess = {fg = "#3dd177"},
    healthWarning = {fg = "#ffc900"},
    helpCommand = {fg = "#d19a66"},
    helpHeader = {fg = "#fefefe"},
    helpHyperTextJump = {fg = "#00b0ff"},
    helpSectionDelim = {fg = "#3dd177"},
    htmlArg = {link = "Type"},
    htmlBold = {bold = true},
    htmlBoldItalic = {bold = true, italic = true},
    htmlBoldItalicUnderline = {link = "htmlBoldUnderlineItalic"},
    htmlBoldUnderline = {bold = true, underline = true},
    htmlBoldUnderlineItalic = {bold = true, italic = true, underline = true},
    htmlComment = {link = "Comment"},
    htmlCommentError = {link = "htmlError"},
    htmlCommentNested = {link = "htmlError"},
    htmlCssDefinition = {link = "Special"},
    htmlCssStyleComment = {link = "Comment"},
    htmlEndTag = {link = "Identifier"},
    htmlError = {link = "Error"},
    htmlEvent = {link = "javaScript"},
    htmlEventDQ = {link = "htmlEvent"},
    htmlEventSQ = {link = "htmlEvent"},
    htmlH1 = {link = "Title"},
    htmlH2 = {link = "htmlH1"},
    htmlH3 = {link = "htmlH2"},
    htmlH4 = {link = "htmlH3"},
    htmlH5 = {link = "htmlH4"},
    htmlH6 = {link = "htmlH5"},
    htmlHead = {link = "PreProc"},
    htmlItalic = {italic = true},
    htmlItalicBold = {link = "htmlBoldItalic"},
    htmlItalicBoldUnderline = {link = "htmlBoldUnderlineItalic"},
    htmlItalicUnderline = {link = "htmlUnderlineItalic"},
    htmlItalicUnderlineBold = {link = "htmlBoldUnderlineItalic"},
    htmlLeadingSpace = {link = "NONE"},
    htmlLink = {link = "Underlined"},
    htmlMath = {},
    htmlMathTagName = {link = "htmlTagName"},
    htmlPreAttr = {link = "String"},
    htmlPreError = {link = "Error"},
    htmlPreProc = {link = "PreProc"},
    htmlPreProcAttrError = {link = "Error"},
    htmlPreProcAttrName = {link = "PreProc"},
    htmlPreStmt = {link = "PreProc"},
    htmlScriptTag = {link = "htmlTag"},
    htmlSpecialChar = {link = "Special"},
    htmlSpecialTagName = {link = "Exception"},
    htmlStatement = {link = "Statement"},
    htmlStrike = {strikethrough = true},
    htmlString = {link = "String"},
    htmlStyleArg = {link = "htmlString"},
    htmlSvg = {},
    htmlSvgTagName = {link = "htmlTagName"},
    htmlTag = {link = "Function"},
    htmlTagError = {link = "htmlError"},
    htmlTagN = {},
    htmlTagName = {link = "htmlStatement"},
    htmlTitle = {link = "Title"},
    htmlUnderline = {underline = true},
    htmlUnderlineBold = {link = "htmlBoldUnderline"},
    htmlUnderlineBoldItalic = {link = "htmlBoldUnderlineItalic"},
    htmlUnderlineItalic = {italic = true, underline = true},
    htmlUnderlineItalicBold = {link = "htmlBoldUnderlineItalic"},
    htmlValue = {link = "String"},
    javaScrParenError = {link = "javaScriptError"},
    javaScript = {link = "Special"},
    javaScriptBoolean = {link = "Boolean"},
    javaScriptBraces = {link = "Function"},
    javaScriptBranch = {link = "Conditional"},
    javaScriptCharacter = {link = "Character"},
    javaScriptComment = {link = "Comment"},
    javaScriptCommentSkip = {},
    javaScriptCommentTodo = {link = "Todo"},
    javaScriptConditional = {link = "Conditional"},
    javaScriptConstant = {link = "Label"},
    javaScriptDebug = {link = "Debug"},
    javaScriptDeprecated = {link = "Exception"},
    javaScriptEmbed = {link = "Special"},
    javaScriptError = {link = "Error"},
    javaScriptException = {link = "Exception"},
    javaScriptExpression = {link = "javaScript"},
    javaScriptFunction = {link = "Function"},
    javaScriptGlobal = {link = "Keyword"},
    javaScriptIdentifier = {link = "Identifier"},
    javaScriptLabel = {link = "Label"},
    javaScriptLineComment = {link = "Comment"},
    javaScriptMember = {link = "Keyword"},
    javaScriptMessage = {link = "Keyword"},
    javaScriptNull = {link = "Keyword"},
    javaScriptNumber = {link = "javaScriptValue"},
    javaScriptOperator = {link = "Operator"},
    javaScriptParens = {},
    javaScriptRegexpString = {link = "String"},
    javaScriptRepeat = {link = "Repeat"},
    javaScriptReserved = {link = "Keyword"},
    javaScriptSpecial = {link = "Special"},
    javaScriptSpecialCharacter = {link = "javaScriptSpecial"},
    javaScriptStatement = {link = "Statement"},
    javaScriptStringD = {link = "String"},
    javaScriptStringS = {link = "String"},
    javaScriptStringT = {link = "String"},
    javaScriptType = {link = "Type"},
    javaScriptValue = {},
    lCursor = {},
    lsp_markdown1 = {},
    markdownAutomaticLink = {link = "markdownUrl"},
    markdownBlockquote = {link = "Comment"},
    markdownBold = {link = "htmlBold"},
    markdownBoldDelimiter = {link = "markdownBold"},
    markdownBoldItalic = {link = "htmlBoldItalic"},
    markdownBoldItalicDelimiter = {link = "markdownBoldItalic"},
    markdownCode = {link = "Special"},
    markdownCodeBlock = {},
    markdownCodeDelimiter = {link = "Delimiter"},
    markdownError = {link = "Error"},
    markdownEscape = {link = "Special"},
    markdownFootnote = {link = "Typedef"},
    markdownFootnoteDefinition = {link = "Typedef"},
    markdownH1 = {link = "htmlH1"},
    markdownH1Delimiter = {link = "markdownHeadingDelimiter"},
    markdownH2 = {link = "htmlH2"},
    markdownH2Delimiter = {link = "markdownHeadingDelimiter"},
    markdownH3 = {link = "htmlH3"},
    markdownH3Delimiter = {link = "markdownHeadingDelimiter"},
    markdownH4 = {link = "htmlH4"},
    markdownH4Delimiter = {link = "markdownHeadingDelimiter"},
    markdownH5 = {link = "htmlH5"},
    markdownH5Delimiter = {link = "markdownHeadingDelimiter"},
    markdownH6 = {link = "htmlH6"},
    markdownH6Delimiter = {link = "markdownHeadingDelimiter"},
    markdownHeadingDelimiter = {link = "Delimiter"},
    markdownHeadingRule = {link = "markdownRule"},
    markdownId = {link = "Type"},
    markdownIdDeclaration = {link = "Typedef"},
    markdownIdDelimiter = {link = "markdownLinkDelimiter"},
    markdownItalic = {link = "htmlItalic"},
    markdownItalicDelimiter = {link = "markdownItalic"},
    markdownLineBreak = {},
    markdownLineStart = {},
    markdownLink = {},
    markdownLinkDelimiter = {},
    markdownLinkText = {link = "htmlLink"},
    markdownLinkTextDelimiter = {},
    markdownListMarker = {link = "htmlTagName"},
    markdownOrderedListMarker = {link = "markdownListMarker"},
    markdownRule = {link = "PreProc"},
    markdownStrike = {link = "htmlStrike"},
    markdownStrikeDelimiter = {link = "markdownStrike"},
    markdownUrl = {link = "Float"},
    markdownUrlDelimiter = {link = "htmlTag"},
    markdownUrlTitle = {link = "String"},
    markdownUrlTitleDelimiter = {link = "Delimiter"},
    markdownValid = {},
    markdownYamlHead = {},
    mkdAmp = {},
    mkdEscape = {link = "Special"},
    mkdGt = {},
    mkdLt = {},
    mkdNbsp = {},
    mkdQuot = {},
    rainbowcol1 = {ctermfg = 9, fg = "#cc241d"},
    rainbowcol2 = {ctermfg = 10, fg = "#a89984"},
    rainbowcol3 = {ctermfg = 11, fg = "#b16286"},
    rainbowcol4 = {ctermfg = 12, fg = "#d79921"},
    rainbowcol5 = {ctermfg = 13, fg = "#689d6a"},
    rainbowcol6 = {ctermfg = 14, fg = "#d65d0e"},
    rainbowcol7 = {ctermfg = 15, fg = "#458588"},
    vbBoolean = {link = "Boolean"},
    vbComment = {link = "Comment"},
    vbConditional = {link = "Conditional"},
    vbConst = {link = "Constant"},
    vbDefine = {link = "Constant"},
    vbError = {link = "Error"},
    vbEvents = {link = "Special"},
    vbFloat = {link = "Float"},
    vbFunction = {link = "Identifier"},
    vbIdentifier = {link = "Identifier"},
    vbKeyword = {link = "Statement"},
    vbLineLabel = {link = "Comment"},
    vbLineNumber = {link = "Comment"},
    vbMethods = {link = "PreProc"},
    vbNumber = {link = "Number"},
    vbOperator = {link = "Operator"},
    vbPreProc = {link = "PreProc"},
    vbRepeat = {link = "Repeat"},
    vbStatement = {link = "Statement"},
    vbString = {link = "String"},
    vbTodo = {link = "Todo"},
    vbTypeSpecifier = {link = "Type"},
    vbTypes = {link = "Type"},
    xmlAttrib = {link = "Type"},
    xmlAttribPunct = {link = "Comment"},
    xmlCdata = {link = "String"},
    xmlCdataCdata = {link = "Statement"},
    xmlCdataEnd = {link = "Type"},
    xmlCdataStart = {link = "Type"},
    xmlComment = {link = "Comment"},
    xmlCommentError = {link = "Error"},
    xmlCommentPart = {link = "Comment"},
    xmlCommentStart = {link = "xmlComment"},
    xmlDocType = {},
    xmlDocTypeDecl = {link = "Function"},
    xmlDocTypeKeyword = {link = "Statement"},
    xmlEndTag = {link = "Identifier"},
    xmlEntity = {link = "Statement"},
    xmlEntityPunct = {link = "Type"},
    xmlEqual = {},
    xmlError = {link = "Error"},
    xmlInlineDTD = {link = "Function"},
    xmlNamespace = {link = "Tag"},
    xmlProcessing = {link = "Type"},
    xmlProcessingDelim = {link = "Comment"},
    xmlRegion = {},
    xmlString = {link = "String"},
    xmlSyncComment = {},
    xmlTag = {link = "Function"},
    xmlTagName = {link = "Function"},
    xmlTodo = {link = "Todo"},
    yamlAlias = {link = "Type"},
    yamlAnchor = {link = "Type"},
    yamlBlockCollectionItemStart = {link = "Label"},
    yamlBlockMappingKey = {link = "Identifier"},
    yamlBlockMappingMerge = {link = "Special"},
    yamlBlockScalarHeader = {},
    yamlBool = {link = "yamlConstant"},
    yamlComment = {link = "Comment"},
    yamlConstant = {link = "Constant"},
    yamlDirective = {},
    yamlDirectiveName = {link = "Keyword"},
    yamlDocumentEnd = {link = "PreProc"},
    yamlDocumentStart = {link = "PreProc"},
    yamlEscape = {link = "SpecialChar"},
    yamlFloat = {link = "Float"},
    yamlFlowCollection = {},
    yamlFlowIndicator = {link = "Special"},
    yamlFlowMapping = {},
    yamlFlowMappingKey = {link = "Identifier"},
    yamlFlowMappingMerge = {link = "Special"},
    yamlFlowString = {link = "yamlString"},
    yamlFlowStringDelimiter = {link = "yamlString"},
    yamlInteger = {link = "Number"},
    yamlKeyValueDelimiter = {link = "Special"},
    yamlMappingKeyStart = {link = "Special"},
    yamlNodeTag = {link = "Type"},
    yamlNull = {link = "yamlConstant"},
    yamlPlainScalar = {},
    yamlReservedDirective = {link = "Error"},
    yamlSingleEscape = {link = "SpecialChar"},
    yamlString = {link = "String"},
    yamlTAGDirective = {link = "yamlDirectiveName"},
    yamlTagHandle = {link = "String"},
    yamlTagPrefix = {link = "String"},
    yamlTimestamp = {link = "Number"},
    yamlTodo = {link = "Todo"},
    yamlYAMLDirective = {link = "yamlDirectiveName"},
    yamlYAMLVersion = {link = "Number"}
}
